name: Release and deploy

on: workflow_dispatch

jobs:
  setVersion: 
    runs-on: ubuntu-latest
    outputs:
      CURRENT_VERSION: ${{ steps.set-current-version.outputs.CURRENT_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set CURRENT_VERSION
        id: set-current-version
        run: echo "CURRENT_VERSION=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
  readVersion: 
    runs-on: ubuntu-latest
    needs: setVersion
    steps:
      - name: Debug CURRENT_VERSION in release
        run: echo "CURRENT_VERSION is ${{ needs.setVersion.outputs.CURRENT_VERSION }}"

